- hosts: all
  become: no
  # vars:
    # user_name: {{ user_name }}
  tasks:
    - name: update apt-get
      sudo: yes
      apt: update_cache=yes
    - name: install basic packages
      sudo: yes
      apt:
        pkg: "{{item}}"
        state: present
      with_items:
        - git
        - tmux
        - zsh
        - vim
  roles:
     - role: avanov.pyenv
       sudo: yes
       pyenv_path: "/home/{{ user_name }}/.pyenv"
       pyenv_owner: "{{ user_name }}"
       pyenv_python_versions:
         - "miniconda3-3.16.0"
       pyenv_virtualenvs: []
     - role: dotfiles
     - role: zsh
